In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.9 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.9 MB 3.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.9/12.9 MB 3.5 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.9 MB 3.6 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/12.9 MB 3.6 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.9 MB 3.6 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.9 MB 3.7 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.9 MB 3.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.9 MB 3.7 MB/s eta 0:00:02
   -------------------------- ------------- 8.7/12.9 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.9 MB 3.8 MB/s eta 0:00:01
   ----------

In [5]:
import numpy as np;
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2=np.array({1,3,5,7,9})
print(arr2)
arr3=np.array((1,3,5,7,9))
print(arr3)
#arr3.reshape()
print(arr3.ndim)
arr4=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr4.ndim)
print(arr4)

{1, 3, 5, 7, 9}
[1 3 5 7 9]
1
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#2d array
arr2d=np.array([[1,2,3,4,5]])# no of'[' se pehchno
print(arr2d,"\n",arr2d.ndim)
#arr2d.reshape(1,5)
print(arr2d.shape)
print(arr2d,"\n",arr2d.ndim)

arrx=np.array([[1,2,3],[4,5,6]])
print(arrx.shape,"\n",arrx)

[[1 2 3 4 5]] 
 2
(1, 5)
[[1 2 3 4 5]] 
 2
(2, 3) 
 [[1 2 3]
 [4 5 6]]


In [ ]:
print(np)

#np.arange(0,1,2,3).reshape(4,1)
t=np.ones((4,4))
print(t)
#identity matrix
i=np.eye(3)
print(i)


<module 'numpy' from 'c:\\Projects\\DataScience\\venv\\lib\\site-packages\\numpy\\__init__.py'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(t.dtype)
print(t.itemsize)  #no of elements 

float64
8


In [36]:
#numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#element wise(same index) add,sub
print("add res=",arr1+arr2)
print("diff res=",arr1-arr2)
print("product res=",arr1*arr2)
print("div res=",arr1/arr2)

add res= [11 22 33 44 55]
diff res= [ -9 -18 -27 -36 -45]
product res= [ 10  40  90 160 250]
div res= [0.1 0.1 0.1 0.1 0.1]


In [44]:
#universal fn
a1=np.array([1,2,3,4,5])
#sq root
print(np.sqrt(a1))

for i in range(5):
    print(np.pow(a1[i],2))

print( np.exp(a1))
print(np.sin(a1),"\n",np.cos(a1),"\n",np.tan(a1))
print(np.log(a1))

[1.         1.41421356 1.73205081 2.         2.23606798]
1
4
9
16
25
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427] 
 [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219] 
 [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [55]:
#array slicing and indexing
arrnew=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arrnew)

for i in range(3):
    for j in range(3):
     print(arrnew[i][j])

#slicing
arrnew[1:,2]

arrnew[0:2,1:]
arrnew[1:3,1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
4
5
6
7
8
9


array([[5, 6],
       [8, 9]])

In [58]:
#array modify
arrnew[0,0]=100
print(arrnew)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
#statistical concept
#--normalization
data=np.array([1,2,3,4,5])

#calculating mean and std deviation
mean=np.mean(data)
stdev=np.std(data)
#vare=np.v(data)

normalize_data=(data-mean)/stdev
print(normalize_data)

AttributeError: module 'numpy' has no attribute 'v'

In [63]:
#logical operation

data>=5
data[data>5]

array([], dtype=int64)